name: Create and Upload File

on:
  push:
    branches:
      - main

jobs:
  create-and-upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create File
        run: echo "This is a sample file" > sample.txt

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sample.txt
          git commit -m "Add sample file"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main

      - name: Upload File to Main Branch
        uses: actions/upload-artifact@v2
        with:
          name: sample-file
          path: ./sample.txt
