name: Excel to HTML

on: 
  workflow_dispatch:

jobs:
  build:
  runs-on: macos-latest

  steps:
  - uses: actions/checkout@v1
  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  - name: Run Python Script
    run: |
      python -m pip install pandas openpyxl
      python excel-html.py
  - name: switching from HTTPS to SSH
    run: git remote set-url origin ${{ secrets.ssh }}
  - name: check for changes
    run: git status
  - name: stage changed files
    run: git add .
  - name: commit changed files
    run: git commit -m "AUTO adding index.html"
  - name: fetch from master
    run: git fetch origin master
  - name: push code to master
    run: git push origin HEAD:master
