name: Generate HTML from Excel and Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository into the workflow
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      # Run the Python script to generate HTML
      - name: Generate HTML
        run: python excel-html.py

      # Upload the generated index.html file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: ./index.html
