name: Python script on commit
on:
  push:
    branches: [ main ]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x' # Version range or exact version of a Node.js version to use, using SemVer's version range syntax
    - name: Install dependencies
      run: |
        npm install # Replace with your package manager command
    - name: Run script
      run: node excel-html.py # Replace with your script name
