name: Generate and push HTML file

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run Python Script
       run: |
        python -m pip install pandas openpyxl
        python excel-html.py

    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Add generated HTML file"
        git push

