name: Excel to HTML

on: 
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Run Python Script
        run: |
          python -m pip install pandas openpyxl
          python excel-html.py

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename -s .git ${{ github.repository }})


      - name: Write file
        run: |
          with open("index.html", 'w') as f:
              f.write("Hello, World!")
              
      - name: Add and commit file
        run: |
          git add index.html
          git commit -m "Add index.html"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
