name: Excel to HTML

on: 
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Run Python Script
        run: |
          python -m pip install pandas openpyxl
          python excel-html.py

      # Upload the generated index.html file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: ./index.html
